src/api/urls.py
from django.urls import path

from api.views import BlogListCreateAPIView
from api.views import UserListCreateAPIView

urlpatterns = [
    path('', BlogListCreateAPIView.as_view(), name='blog_create'),
   
    path('user/', UserListCreateAPIView.as_view(), name='user-list'),
]

src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='blog_create'),
    path('details/(?P<slug>[\w\-]+)/$', views.blog_details, name='blog_detail'),
    path('likes/<pk>/', views.liked, name='liked_post'),
    path('unlikes/<pk>/', views.unliked, name='unliked_post'),
    path('my-blog/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),

]

src/my_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login.urls'), ),
    path('blog/', include('blog.urls')),

    path('', views.index, name='index'),
    path('blog-api/', include('api.urls') ),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author', )
    blog_title = models.CharField(max_length=264, )
    slug = models.SlugField(max_length=264, unique=True, )
    blog_content = models.TextField(verbose_name='What is on your mind?', )
    blog_image = models.ImageField(upload_to='blog-image', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True, )
    update_date = models.DateTimeField(auto_now=True, )

   
   

    class Meta:
        db_table = 'blog'
        ordering = ('-publish_date', )


    
        

    def __str__(self):
        return self.blog_title    


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment', )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment', )
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True, )

    class Meta:
        db_table = 'comment'
        ordering = ('-comment_date', )
       
       
       
    
    def __str__(self):
        return self.comment


class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')      

    class Meta:
        db_table = 'likes'
        verbose_name = 'Like'
        verbose_name_plural = 'Likes'  

    def __str__(self):
        return self.user + 'likes' + self.blog    


     

src/blog/forms.py
from django import forms

from blog.models import Blog, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', )

src/blog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView,View,TemplateView,DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from blog.models import Blog, Comment, Likes
from blog.forms import CommentForm

import uuid




class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = 'blog/my_blogs.html'





class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'blog/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image', )

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(' ', '_') + '_' + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'blog/blog_list.html'

@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    
    already_liked = Likes.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False  


    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('blog:blog_detail', kwargs={'slug':slug}))

    return render(request, 'blog/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked, } )    

@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user

    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        like_post = Likes(blog=blog, user=user)
        like_post.save()
    return HttpResponseRedirect(reverse('blog:blog_detail', kwargs={'slug':blog.slug}))   


@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('blog:blog_detail', kwargs={'slug':blog.slug}))   


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image', )
    template_name = 'blog/edit_blog.html'

    def get_success_url(self):
        return reverse_lazy('blog:blog_detail', kwargs={'slug':self.object.slug})

src/templates/blog/blog_details.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %}{{blog.blog_title}}{% endblock %}
{% block body_block %}

<div class="row">
    <div class="col-sm-6">
        <h2>{{blog.blog_title}}</h2>
        <h4>Posted by: @{{blog.author}}</h4>
        <i><h6> Publish on: {{blog.publish_date}}</h6></i>
        <i><h6>Updated On:{{blog.update_date}}</h6></i>
        <h6>{{blog.blog_likes.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
        
    </div>
    <div class="col-sm-6">
        <img src="/src/media/ {{blog.blog_image}}" alt="" width="100%">
    </div>
    <p>
        {{blog.blog_content|linebreaks}}
    </p>
</div>

<div class="row">
    {% if not liked %}
    <div class="col-sm-1">
        <a href=" {% url 'blog:liked_post' pk=blog.pk %}">
            <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
        </a>
    </div>
    {% else %}
    <div class="col-sm-1">
        <a href="{% url 'blog:unliked_post' pk=blog.pk %}">
            <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
        </a>
    </div>
    {% endif %}
</div>






<div class="row">
    <div class="col-sm-6">
        <hr>
        <h5>Comments</h5>
        {% for comment in blog.blog_comment.all %}
        <p><a href="#">@{{comment.user}}</a> , {{comment.comment}}
            <br>
            <h6>{{comment.comment_date}}</h6>
        </p>
        {% endfor %}
    </div>
    <div class="col-sm-6">
        <form  method="POST">
            {{comment_form|crispy}}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm">comment</button>

        </form>
    </div>
</div>
<br>
<br>
   
{% endblock %}

src/templates/blog/blog_list.html
{% extends 'base.html'%}
{% block title_block %}Home{% endblock %}
{% block body_block %}
{% load custom_filters %}
{% for blog in blogs %}
 <h3>{{blog.blog_title}}</h3>
 
 <h6><i>{{blog.publish_date}}</i></h6>
 
 <div class="row">
    <div class="col-sm-4">
       <img src="/src/media/{{ blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.title}}" width="100%">
    </div>
    
    <div class="col-sm-8">
       <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'blog:blog_detail' slug=blog.slug %}">Read more</a></p>
       <h6>Posted by: <a href="#">{{blog.author}} </a> </h6>
       <h6>{{ blog.blog_likes.count}} Likes | {{blog.blog_comment.count}} comments</h6>
    </div>
 </div>
 <hr>
{% endfor %}
{% endblock %}

src/templates/blog/create_blog.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %}create blog{% endblock %}
{% block body_block %}
<h2>Write your blog here:</h2>
<form method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>
   
{% endblock %}

src/templates/blog/edit_blog.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %}{{ blog.blog_title}}{% endblock %}
{% block body_block %}
{% if blog.author == user %}
<form  method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" name="button">Update</button>
    {% else %}
    <p>You are not allowed to view this page. 404</p>
    
</form>
<hr>
{% endif %}
  
{% endblock %}

src/templates/blog/my_blogs.html
{% extends 'base.html'%}
{% load custom_filters %}
{% block title_block %}{{ user }}{% endblock %}
{% block body_block %}
{% for blog in user.post_author.all %}
<h3>{{blog.blog_title}}</h3>
<h6>{{blog.publish_date}}</h6>
<div class="row">
    <div class="col-sm-5">
        <img src="/src/media/{{ blog.blog_image}}" width="100%">
    </div>
    <div class="col-sm-7">
        <p>{{blog.blog_content|range_filter|linebreaks}}</p>
        <a href="{% url 'blog:blog_detail' slug=blog.slug%}">Read more</a>
    </div>
</div>
<br>

<a href="{% url 'blog:edit_blog' pk=blog.pk %}">Edit</a>
<hr>

{% endfor %}
   
{% endblock %}