src/api/urls.py
from django.urls import path

from api.views import BlogListCreateAPIView
from api.views import UserListCreateAPIView

urlpatterns = [
    path('', BlogListCreateAPIView.as_view(), name='blog_create'),
   
    path('user/', UserListCreateAPIView.as_view(), name='user-list'),
]

src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='blog_create'),
    path('details/(?P<slug>[\w\-]+)/$', views.blog_details, name='blog_detail'),
    path('likes/<pk>/', views.liked, name='liked_post'),
    path('unlikes/<pk>/', views.unliked, name='unliked_post'),
    path('my-blog/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),

]

src/login/urls.py
from django.urls import path
from . import views



app_name = 'login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'), 
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('change-profile/', views.user_change, name='change_user'), 
    path('password/', views.pass_change, name='changed_passord'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

src/my_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login.urls'), ),
    path('blog/', include('blog.urls')),

    path('', views.index, name='index'),
    path('blog-api/', include('api.urls') ),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- latest compiled and minified css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- jquery Library -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

    <!-- PopperJs -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

    <!-- Latest compiled Javascript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title_block %} Blogs {% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}"><img src="/src/media/logo.png" alt="logo-image" width="50px"></a>
            </li>

            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown" data-toggle="dropdown">
                    @{{user.username}}
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'blog:blog_create' %}">Write blog</a>
                    <a class="dropdown-item" href="{% url 'login:profile' %}"> Your Profile</a>
                    <a class="dropdown-item" href="{% url 'blog:my_blogs' %}"> My Blogs</a>
                    <hr>
                    <a class="dropdown-item" href="{% url 'login:logout' %}"> Logout</a>
                </div>
            </div>
            
            {% else %}
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'login:signup' %}">Sign Up</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'login:login' %}">Login</a>
            </li>
            {% endif %}

        </ul>
    </nav>
    <div class="container p-4">
        {% block body_block %}

        {% endblock %}
    </div>

</body>

</html>