src/api/urls.py
from django.urls import path

from api.views import BlogListCreateAPIView
from api.views import UserListCreateAPIView

urlpatterns = [
    path('', BlogListCreateAPIView.as_view(), name='blog_create'),
   
    path('user/', UserListCreateAPIView.as_view(), name='user-list'),
]

src/login/urls.py
from django.urls import path
from . import views



app_name = 'login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'), 
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('change-profile/', views.user_change, name='change_user'), 
    path('password/', views.pass_change, name='changed_passord'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

src/my_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login.urls'), ),
    path('blog/', include('blog.urls')),

    path('', views.index, name='index'),
    path('blog-api/', include('api.urls') ),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/login/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics')
    

src/login/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from login.models import UserProfile


class SignupForm(UserCreationForm):
    email = forms.EmailField(label='Email Adddress', required=True, )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password', )


        
class ProfilePic(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic', ]
        

src/login/views.py
from django.shortcuts import render

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate,login, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from login.forms import SignupForm, UserProfileChange,ProfilePic







def sign_up(request):
    form = SignupForm()
    registered = False
    if request.method == 'POST':
        form = SignupForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    dict = {'form':form, 'registerd':registered}

    return render(request, 'login/signup.html', context=dict)    



def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

    return render(request, 'login/login.html', context={'form':form}) 

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))   

@login_required
def user_profile(request):
    return render(request, 'login/profile.html', context={})    

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
            
    return render(request, 'login/change_profile.html', context={'form':form}) 

@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'login/change_pass.html', context={'form':form, 'changed':changed})        



@login_required

def add_pro_pic(request):
    form = ProfilePic
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('login:profile'))
    return render(request, 'login/pro_pic_add.html', context={'form':form}, )

@login_required

def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == "POST":
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login:profile'))


    return render(request, 'login/pro_pic_add.html', context={'form':form})

src/templates/login/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}change_pass{% endblock %}
{% block body_block %}
{% if Changed %}
<div class="alert alert-success">
    password Changed SuccessFully
</div>
{% else %}

<form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Change Password</button>

</form>
{% endif %}
{% endblock %}

src/templates/login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}change_profile{% endblock %}
{% block body_block %}
   <form method="POST">
       {{form|crispy}}
       {% csrf_token %}
       <button type="submit" class="btn btn-warning btn-sm">Change</button>
      
   </form>
{% endblock %}

src/templates/login/login.html
{% extends "base.html" %}
{% load  crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block body_block %}
  <h2>Login:</h2>
  <form method="POST">
      {{form|crispy}}
      {% csrf_token %}
      <button type="submit" class="btn btn-primary btn-success">Login</button>
  </form>
{% endblock %}

src/templates/login/pro_pic_add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}Profile Picture{% endblock %}
{% block body_block%}
  
  <h2>Upload Your Profile Picture</h2>
  <form method="POST" enctype="multipart/form-data">
      {{form|crispy}}
      {% csrf_token %}
      <button type="submit" class="btn btn-success btn-sm"> Add</button>

  </form>


{% endblock %}

src/templates/login/profile.html
{% extends "base.html" %}
{% block title_block %}Your Profile {% endblock %}
{% block body_block%}

<h2>Your Profile</h2>
{% if user.user_profile %}
<img src="/src/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="100px">

<br>

<a href="{% url 'login:change_pro_pic' %}" class="btn btn-info btn-sm ">Change
Profile Picture</a>
<br>
{% else %}
<img src="/src/media/profile_pics/avatar-male.jpg" class="rounded-circle" width="100px">
<br>

<a href="{% url 'login:add_pro_pic' %}" class="btn btn-info btn-sm ">Upload Profile Picture</a>
<br>
{% endif %}
<br>
<p><Username:> Username:{{ user.username }} </Username:></p>
<p>Email: {{ user.email }}</p>
<p>Name: {{ user.first_name}} {{ user.last_name }}</p>
<br>
<a href="{% url 'login:change_user' %}" class="btn btn-warning btn-sm">Change profile info </a>

{% endblock  %}

src/templates/login/signup.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %}Sign Up{% endblock %}
{% block body_block %}
{% if registered %}
<div class="alert alert-success">
    Account Created Successfully! <a href="{% url 'login:login' %}"> Login here</a>
</div>

{% else %}
<h2>Create New Account:</h2>
<form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">create Account</button>
</form>
<br>
<p>Already have an account? <a href="{% url 'login:login'%}">Login here</a> </p>
{% endif %}
{% endblock %}